- README.md
Initial draft of the information we are required to submit by 11:59 on 2/14.
> added basic project information to the readme file

- email.txt
Here is my first draft of the email, change anything y'all want!
> Peter's first email draft

- email.txt
Streamlined the wording of the email message.
> Tweaked wording of message

- component_specification.md
- data_sources.md
Per our discussion in class on 2/14 I have compiled the list of questions, sub-questions and links to data sources necessary to answer them in the GitHub.
> Created file with research questions, sub-questions, and data sources

- README.md
- doc/developer.md
Added readme file for installation of camelot, and information on how to find document in README.
> Installation README changes 

- doc/developer.md
Fixed formatting issues in doc/dev readme
> Fixed some formatting issues

- WisconsinWolfAnalysis/test_camelot.py
This is a very simple test. It doesn't actually test a package, just imports camelot and uses it on of the example files that produces a blank table. 
I chose to put it in a separate file to make future cleanup easier.
> added test_camelot.py file with a smoke test to see if camelot runs in the CI environment

- doc/min_environment.yml
Remove non-essential packages from yml file
In the future will be writing CI document to this
> Remove non-essential packages from yml file

- WisconsinWolfAnalysis/stats_module.py
Did something weird with my branches. Re-pushing the changes to the stats module and test file
> Re-pushing changes to stats module and test

- doc/Component_Specifications.md
@ekrolen I am not stealing your thunder by having an output of my function be a line chart for the "numerators" of my proportions, right? I just wanted to make sure since Hypothesis Function 2 will also be outputting line charts.
> Added Hyp Function 3 description to Comp Spec

- doc/min_environment.yml
Needed to add ghostscript (my favorite package) back into the environment file
> updated min environment

- build_test.yml
Created a copy of build_test.yml from class
Will make specific after meeting tonight
Adding to GH after meeting and specifications
Will enforce ??
> Created copy of build_test.yml from class

- WisconsinWolfAnalysis/stats_module.py
- WisconsinWolfAnalysis/stats_wrapper.py
- WisconsinWolfAnalysis/test_stats_module.py
1st draft of my function is ready to be merged.
> Logan Hypothesis 3 function

- environment.yml
removed ".16" from end of python version to make it more compatible w/ the CI documentation
> removed specific version from python

- WisconsinWolfAnalysis/stats_module.py
- WisconsinWolfAnalysis/test_stats_module.py
Linted the stats module - passes 10/10 but ignored some enumerates and too many local variables
> E linted stats_module

- WisconsinWolfAnalysis/test_stats_module.py
Mock got removed from the stats module tester
> added back in mocking

- WisconsinWolfAnalysis/stats_wrapper.py
added a . to tell the stats wrapper where to look for stats module - testing locally now
> clarified path in stats wrapper

- WisconsinWolfAnalysis/pdf_parser.py
The functionality of the program needs to be re-tested, due to minor changes in code. Maybe @kevintorrico can help out with this.
> Pylint score 10/10 to pdf_parser

- doc/Functional_Specification.md
Removed a line about the components of our design, as I believe that is out of scope for this document.
> Update functional specification

- doc/Functional_Specification.md
Changed the order of the use cases to flow from least to greatest interaction with our work
> Updated functional specification document

- examples/pdf_parser_example_walkthrough.md
Changed file name of development.md to developer.md to match the current file name in the repo.
> Updated pdf parser example md
